# -*- coding: utf-8 -*-
"""ARISTEKTUR TA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D8adwCVTBY8uccb5Gp4in4iza6MetLLV
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -q ultralytics timm

import os
import torch
import torch.nn as nn
import timm
import yaml
from ultralytics import YOLO
from ultralytics.nn import tasks
import ultralytics.nn.modules.conv as conv_modules

print("\n--- Menyalin dan Mengekstrak Dataset ---")
!cp /content/drive/MyDrive/RDD2022_JP_YOLO/RDD2022_JP_YOLO_v2.zip /content/
!unzip -q /content/RDD2022_JP_YOLO_v2.zip -d /content/rdd_data/
print("Dataset berhasil disiapkan di: /content/rdd_data/")

"""##**YOLOV8N**"""

# TAHAP TRAINING MODEL BASELINE: YOLOv8n STANDAR (ORIGINAL)
from ultralytics import YOLO

print("\n--- Memulai Training YOLOv8n Standar (Baseline) ---")
model_standar = YOLO('yolov8n.pt')

model_standar.train(
    data='/content/drive/MyDrive/RDD2022_JP_YOLO/rdd_data_jp_local.yaml', # Path dataset Anda
    epochs=50,
    imgsz=640,
    batch=16,
    name='yolov8n',
    project='yolo_comparison_test'
)

print("\n Training YOLOv8n Standar Selesai!")

"""### Daftar Parameter Training (Ultralytics v8.4.48)

| Kategori | Parameter | Nilai | Deskripsi |
| :--- | :--- | :--- | :--- |
| **Utama** | `epochs` | 50 | Total siklus pelatihan |
| | `imgsz` | 640 | Resolusi input gambar |
| | `batch` | 16 | Jumlah gambar per batch |
| **Optimizer** | `optimizer` | Auto (SGD) | Algoritma optimasi bobot |
| | `lr0` | 0.01 | Initial Learning Rate |
| | `lrf` | 0.01 | Final Learning Rate |
| | `momentum` | 0.937 | Faktor momentum gradien |
| | `weight_decay` | 0.0005 | Penalti pencegahan overfitting |
| **Loss Gain** | `box` | 7.5 | Bobot penalti Box Loss |
| | `cls` | 0.5 | Bobot penalti Classification Loss |
| | `dfl` | 1.5 | Bobot Distribution Focal Loss |
| **Augmentasi** | `mosaic` | 1.0 | Probabilitas penggabungan 4 gambar |
| | `close_mosaic`| 10 | Mematikan mosaic di 10 epoch akhir |
| | `warmup_epochs`| 3.0 | Fase pemanasan awal |
| **Lainnya** | `iou` | 0.7 | Ambang batas Intersection over Union |

"""

# MENGHITUNG METRIK LENGKAP (YOLOv8n STANDAR)
print("\n--- Menghitung Metrik Lengkap (YOLOv8n Standar) ---")
model_eval = YOLO('/content/runs/detect/yolo_comparison_test/yolov8n/weights/best.pt')

# Lakukan validasi ulang secara singkat
metrik = model_eval.val(data='/content/drive/MyDrive/RDD2022_JP_YOLO/rdd_data_jp_local.yaml')

# Panggil metrik spesifik
print("\n=== HASIL EVALUASI YOLOv8n STANDAR ===")
print(f"mAP@50    : {metrik.box.map50:.4f}")
print(f"mAP@75    : {metrik.box.map75:.4f}")
print(f"mAP@50-95 : {metrik.box.map:.4f}")

"""##**YOLOV8N + MOBILENETV3 SMALL**

"""

# TAHAP 1: CUSTOM LAYER REGISTRATION (LAYER ADAPTER)
class Select_Explicit_Fix(nn.Module):
    def __init__(self, c1, c2, index=0, **kwargs):
        super().__init__()
        self.index = index

    def forward(self, x):
        if isinstance(x, list):
            return x[self.index]
        return x

# Override modul agar YOLO mengenali selector custom
conv_modules.GhostConv = Select_Explicit_Fix
tasks.GhostConv = Select_Explicit_Fix

# TAHAP 2: DEFINISI BACKBONE (MOBILENET V3 SMALL)
MODEL_NAME = 'mobilenetv3_small_100'
CORRECT_INDICES = [2, 3, 4]

class MobileNetV3Backbone(nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__()
        self.model = timm.create_model(
            MODEL_NAME, features_only=True, out_indices=CORRECT_INDICES, pretrained=True, in_chans=3
        )
    def forward(self, x):
        return self.model(x)

tasks.MobileNetV3Backbone = MobileNetV3Backbone

# Ambil dimensi channel asli dari MobileNet secara otomatis
tmp_model = timm.create_model(MODEL_NAME, features_only=True, out_indices=CORRECT_INDICES, pretrained=False)
tmp_out = tmp_model(torch.randn(1, 3, 640, 640))
REAL_CHANNELS = [x.shape[1] for x in tmp_out]
print(f"Dimensi Channel Backbone: {REAL_CHANNELS}")

# TAHAP 3: KONFIGURASI ARSITEKTUR YAML
yaml_filename = 'yolov8n_mbv3.yaml'

config_content = {
    'nc': 4,
    'scales': {'n': [0.33, 1.00, 1024]},
    'backbone': [
        [-1, 1, 'MobileNetV3Backbone', []],
        [0, 1, 'GhostConv', [REAL_CHANNELS[0], 0]], # P3
        [0, 1, 'GhostConv', [REAL_CHANNELS[1], 1]], # P4
        [0, 1, 'GhostConv', [REAL_CHANNELS[2], 2]], # P5
        [-1, 1, 'SPPF', [256, 5]]
    ],
    'head': [
        [-1, 1, 'nn.Upsample', [None, 2, 'nearest']],
        [[-1, 2], 1, 'Concat', [1]],
        [-1, 3, 'C2f', [64]],

        [-1, 1, 'nn.Upsample', [None, 2, 'nearest']],
        [[-1, 1], 1, 'Concat', [1]],
        [-1, 3, 'C2f', [64]],

        [-1, 1, 'Conv', [64, 3, 2]],
        [[-1, 7], 1, 'Concat', [1]],
        [-1, 3, 'C2f', [128]],

        [-1, 1, 'Conv', [128, 3, 2]],
        [[-1, 4], 1, 'Concat', [1]],
        [-1, 3, 'C2f', [256]],

        [[10, 13, 16], 1, 'Detect', ['nc']]
    ]
}

with open(yaml_filename, 'w') as f:
    yaml.dump(config_content, f, sort_keys=False)

# TAHAP 4: INISIALISASI & TRAINING
print(f"\n--- Memulai Training YOLOv8n + MobileNetV3 ---")
model = YOLO(yaml_filename)

model.train(
    data='/content/drive/MyDrive/RDD2022_JP_YOLO/rdd_data_jp_local.yaml',
    epochs=50,
    imgsz=640,
    batch=16,
    name='yolov8n_mbv3',
    project='yolo_comparison_test'
)

model_eval = 'YOLO'(path/best.pt)
metrik = model_eval.val(path/image001.png)

print (metrik)

# MENGHITUNG METRIK LENGKAP (YOLOv8n + MobileNetV3)
print("\n--- Menghitung Metrik Lengkap (YOLOv8n + MobilNetv3) ---")
model_eval = YOLO('/content/runs/detect/yolo_comparison_test/yolov8n_mbv3/weights/best.pt')

# Lakukan validasi ulang secara singkat
print("\n--- Menghitung Metrik Lengkap ---")
metrik = model_eval.val(data='/content/drive/MyDrive/RDD2022_JP_YOLO/rdd_data_jp_local.yaml')

# Panggil metrik spesifik
print(f"mAP@50    : {metrik.box.map50:.4f}")
print(f"mAP@75    : {metrik.box.map75:.4f}")
print(f"mAP@50-95 : {metrik.box.map:.4f}")

"""### Konfigurasi Training Modifikasi (MobileNetV3 Standar Tanpa Tuning)

| Kategori | Parameter | Nilai | Deskripsi |
| :--- | :--- | :--- | :--- |
| **Utama** | `model` | yolov8n_mbv3.yaml | Arsitektur modifikasi MobileNetV3 |
| | `imgsz` | 640 | Resolusi input gambar |
| | `epochs` | 50 | Total siklus pelatihan |
| | `batch` | 16 | Jumlah sampel per batch |
| **Optimizer** | `optimizer` | Auto (SGD) | Algoritma optimasi bobot |
| | `lr0` | 0.01 | Initial Learning Rate |
| | `momentum` | 0.937 | Faktor momentum gradien |
| | `weight_decay` | 0.0005 | Penalti regularisasi |
| **Loss Gain** | `box` | 7.5 | Bobot penalti Box Loss |
| | `cls` | 0.5 | Bobot penalti Classification Loss |
| | `dfl` | 1.5 | Bobot Distribution Focal Loss |
| **Augmentasi** | `mosaic` | 1.0 | Aktif (Penggabungan 4 gambar) |
| | `close_mosaic`| 10 | Mosaic dimatikan pada 10 epoch terakhir |
| | `warmup_epochs`| 3.0 | Durasi fase pemanasan awal |
| **Lainnya** | `iou` | 0.7 | NMS Threshold (Penyaringan kotak dobel) |

##**HYPERPARAMETER**
"""

# TAHAP 1: CUSTOM LAYER REGISTRATION (LAYER ADAPTER)
class Select_Explicit_Fix(nn.Module):
    def __init__(self, c1, c2, index=0, **kwargs):
        super().__init__()
        self.index = index

    def forward(self, x):
        if isinstance(x, list):
            return x[self.index]
        return x

# Override modul agar YOLO mengenali selector custom
conv_modules.GhostConv = Select_Explicit_Fix
tasks.GhostConv = Select_Explicit_Fix

# TAHAP 2: DEFINISI BACKBONE (MOBILENET V3 SMALL)
MODEL_NAME = 'mobilenetv3_small_100'
CORRECT_INDICES = [2, 3, 4]

class MobileNetV3Backbone(nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__()
        self.model = timm.create_model(
            MODEL_NAME, features_only=True, out_indices=CORRECT_INDICES, pretrained=True, in_chans=3
        )
    def forward(self, x):
        return self.model(x)

tasks.MobileNetV3Backbone = MobileNetV3Backbone

# Ambil dimensi channel asli dari MobileNet secara otomatis
tmp_model = timm.create_model(MODEL_NAME, features_only=True, out_indices=CORRECT_INDICES, pretrained=False)
tmp_out = tmp_model(torch.randn(1, 3, 640, 640))
REAL_CHANNELS = [x.shape[1] for x in tmp_out]
print(f"Dimensi Channel Backbone: {REAL_CHANNELS}")

# TAHAP 3: KONFIGURASI ARSITEKTUR YAML
yaml_filename = 'yolov8n_mbv3.yaml'

config_content = {
    'nc': 4,
    'scales': {'n': [0.33, 1.00, 1024]},
    'backbone': [
        [-1, 1, 'MobileNetV3Backbone', []],
        [0, 1, 'GhostConv', [REAL_CHANNELS[0], 0]], # P3
        [0, 1, 'GhostConv', [REAL_CHANNELS[1], 1]], # P4
        [0, 1, 'GhostConv', [REAL_CHANNELS[2], 2]], # P5
        [-1, 1, 'SPPF', [256, 5]]
    ],
    'head': [
        [-1, 1, 'nn.Upsample', [None, 2, 'nearest']],
        [[-1, 2], 1, 'Concat', [1]],
        [-1, 3, 'C2f', [64]],

        [-1, 1, 'nn.Upsample', [None, 2, 'nearest']],
        [[-1, 1], 1, 'Concat', [1]],
        [-1, 3, 'C2f', [64]],

        [-1, 1, 'Conv', [64, 3, 2]],
        [[-1, 7], 1, 'Concat', [1]],
        [-1, 3, 'C2f', [128]],

        [-1, 1, 'Conv', [128, 3, 2]],
        [[-1, 4], 1, 'Concat', [1]],
        [-1, 3, 'C2f', [256]],

        [[10, 13, 16], 1, 'Detect', ['nc']]
    ]
}

with open(yaml_filename, 'w') as f:
    yaml.dump(config_content, f, sort_keys=False)

# TAHAP 4: MANUAL TUNING - SKENARIO 1
print(f"\n--- Memulai Manual Tuning (Learning Rate: 0.001) ---")
model = YOLO('yolov8n_mbv3.yaml')

model.train(
    data='/content/drive/MyDrive/RDD2022_JP_YOLO/rdd_data_jp_local.yaml',
    epochs=10,
    imgsz=640,
    batch=16,
    lr0=0.001,
    name='yolov8n_mbv3_manual_S1',
    project='yolo_tuning_test'
)

# TAHAP 4: MANUAL TUNING - SKENARIO 2
print(f"\n--- Eksperimen Skenario 2: Mencari Kecepatan Konvergensi (LR: 0.005) ---")
model = YOLO('yolov8n_mbv3.yaml')

model.train(
    data='/content/drive/MyDrive/RDD2022_JP_YOLO/rdd_data_jp_local.yaml',
    epochs=10,
    imgsz=640,
    batch=16,
    lr0=0.005,       # Menengah antara 0.01 (default) dan 0.001 (S1)
    warmup_epochs=2, # Tancap gas lebih awal
    name='yolov8n_mbv3_manual_S2',
    project='yolo_tuning_test'
)

# TAHAP 4: MANUAL TUNING - SKENARIO 3
print(f"\n--- Eksperimen Skenario 3: Optimizer AdamW & Mosaic Tuning (LR: 0.005) ---")
model = YOLO('yolov8n_mbv3.yaml')

model.train(
    data='/content/drive/MyDrive/RDD2022_JP_YOLO/rdd_data_jp_local.yaml',
    epochs=10,
    imgsz=640,
    batch=16,
    lr0=0.005,
    optimizer='AdamW', # Ganti optimizer
    mosaic=0.5,        # Sesuaikan augmentasi
    warmup_epochs=2,
    name='yolov8n_mbv3_manual_S3',
    project='yolo_tuning_test'
)

# TAHAP 4: MANUAL TUNING - SKENARIO 4 (Augmentation Boost)
print(f"\n--- Eksperimen Skenario 4: Mixup & Copy-Paste (LR: 0.005) ---")
model = YOLO('yolov8n_mbv3.yaml')

model.train(
    data='/content/drive/MyDrive/RDD2022_JP_YOLO/rdd_data_jp_local.yaml',
    epochs=10,
    imgsz=640,
    batch=16,
    lr0=0.005,
    optimizer='SGD',
    warmup_epochs=2,
    mixup=0.2,         # Menambah kesulitan data
    copy_paste=0.1,    # Menambah variasi posisi objek
    degrees=10.0,      # Variasi rotasi
    name='yolov8n_mbv3_manual_S4',
    project='yolo_tuning_test'
)

# TAHAP 4: MANUAL TUNING - SKENARIO 6 (High Momentum)
model = YOLO('yolov8n_mbv3.yaml')

model.train(
    data='/content/drive/MyDrive/RDD2022_JP_YOLO/rdd_data_jp_local.yaml',
    epochs=10,
    imgsz=640,
    batch=16,
    lr0=0.005,
    optimizer='SGD',
    momentum=0.98,     # Naikkan momentum
    warmup_epochs=2,
    name='yolov8n_mbv3_manual_S6',
    project='yolo_tuning_test'
)

# TAHAP 4: MANUAL TUNING - SKENARIO 5 (IMG Size)
print(f"\n--- Memulai Training YOLOv8n + MobileNetV3 (Resolution 800) ---")
model = YOLO('yolov8n_mbv3.yaml')

model.train(
    data='/content/drive/MyDrive/RDD2022_JP_YOLO/rdd_data_jp_local.yaml',
    epochs=10,
    imgsz=800,
    batch=16,
    name='yolov8n_mbv3_manual_S5',
    project='yolo_tuning_test'
)

"""##**TUNING - 1 (BEST)**

"""

print(f"\n--- Memulai Training ---")
model = YOLO('yolov8n_mbv3.yaml')

model.train(
    data='/content/drive/MyDrive/RDD2022_JP_YOLO/rdd_data_jp_local.yaml',
    epochs=50,
    imgsz=800,
    batch=16,
    lr0=0.01,
    optimizer='SGD',
    warmup_epochs=3,
    close_mosaic=15,
    label_smoothing=0.1,
    name='yolov8n_mbv3_tuning',
    project='yolo_tuning_test'
)

"""### Konfigurasi Training Modifikasi (MobileNetV3 Tuning)

| Kategori | Parameter | Nilai | Deskripsi |
| :--- | :--- | :--- | :--- |
| **Utama** | `model` | yolov8n_mbv3.yaml | Arsitektur modifikasi MobileNetV3 |
| | `imgsz` | 800 | Resolusi input gambar (High Resolution) |
| | `epochs` | 50 | Total siklus pelatihan |
| | `batch` | 16 | Jumlah sampel per batch |
| **Optimizer** | `optimizer` | SGD | Stochastic Gradient Descent |
| | `lr0` | 0.01 | Initial Learning Rate |
| | `momentum` | 0.937 | Faktor momentum gradien |
| | `weight_decay` | 0.0005 | Penalti regularisasi |
| **Loss Gain** | `box` | 7.5 | Bobot penalti Box Loss |
| | `cls` | 0.5 | Bobot penalti Classification Loss |
| | `dfl` | 1.5 | Bobot Distribution Focal Loss |
| **Augmentasi** | `mosaic` | 1.0 | Aktif (Penggabungan 4 gambar) |
| | `close_mosaic`| 15 | Mosaic dimatikan pada 15 epoch terakhir |
| | `warmup_epochs`| 3 | Durasi fase pemanasan awal |
| **Lainnya** | `iou` | 0.7 | NMS Threshold (Penyaringan kotak dobel) |

"""

from ultralytics import YOLO

model_eval = YOLO('/content/runs/detect/yolo_tuning_test/yolov8n_mbv3_tuning/weights/best.pt')

# Lakukan validasi ulang secara singkat
print("\n--- Menghitung Metrik Lengkap ---")
metrik = model_eval.val(data='/content/drive/MyDrive/RDD2022_JP_YOLO/rdd_data_jp_local.yaml')

# Panggil metrik spesifik
print(f"mAP@50    : {metrik.box.map50:.4f}")
print(f"mAP@75    : {metrik.box.map75:.4f}")
print(f"mAP@50-95 : {metrik.box.map:.4f}")

"""##**TUNING - 2**"""

from ultralytics import YOLO

print("\n--- Memulai Training Final: Modifikasi + Partial Freezing ---")
model = YOLO('yolov8n_mbv3.yaml')

model.train(
    data='/content/drive/MyDrive/RDD2022_JP_YOLO/rdd_data_jp_local.yaml',
    epochs=50,
    imgsz=640,
    batch=32,
    freeze=10,
    lr0=0.01,
    optimizer='SGD',
    label_smoothing=0.1,
    name='yolov8n_mbv3_tuning_frozen',
    project='yolo_tuning_test'
)

"""### Konfigurasi Training Modifikasi (Partial Freezing)

| Kategori | Parameter | Nilai | Deskripsi |
| :--- | :--- | :--- | :--- |
| **Utama** | `model` | yolov8n_mbv3.yaml | Arsitektur modifikasi MobileNetV3 |
| | `imgsz` | 640 | Resolusi input gambar |
| | `epochs` | 50 | Total siklus pelatihan |
| | `batch` | 32 | Jumlah sampel per batch (Batch lebih besar) |
| **Optimasi** | `optimizer` | SGD | Stochastic Gradient Descent |
| | `lr0` | 0.01 | Initial Learning Rate |
| | `freeze` | 10 | Membekukan 10 layer pertama (Partial Freeze) |
| | `warmup_epochs`| 3.0 | Durasi fase pemanasan awal |
| **Loss Gain** | `box` | 7.5 | Bobot penalti Box Loss |
| | `cls` | 0.5 | Bobot penalti Classification Loss |
| | `dfl` | 1.5 | Bobot Distribution Focal Loss |
| **Augmentasi** | `mosaic` | 1.0 | Aktif (Penggabungan 4 gambar) |
| | `close_mosaic`| 10 | Mosaic dimatikan pada 10 epoch terakhir |
| **Lainnya** | `iou` | 0.7 | NMS Threshold (Penyaringan kotak dobel) |
"""

from ultralytics import YOLO

model_eval = YOLO('/content/runs/detect/yolo_tuning_test/yolov8n_mbv3_tuning_frozen-2/weights/best.pt')

# Lakukan validasi ulang secara singkat
print("\n--- Menghitung Metrik Lengkap ---")
metrik = model_eval.val(data='/content/drive/MyDrive/RDD2022_JP_YOLO/rdd_data_jp_local.yaml')

# Panggil metrik spesifik
print(f"mAP@50    : {metrik.box.map50:.4f}")
print(f"mAP@75    : {metrik.box.map75:.4f}")
print(f"mAP@50-95 : {metrik.box.map:.4f}")

"""##**TUNING - 3**"""

from ultralytics import YOLO

model = YOLO('yolov8n_mbv3.yaml')

model.train(
    data='/content/drive/MyDrive/RDD2022_JP_YOLO/rdd_data_jp_local.yaml',
    epochs=50,
    imgsz=800,
    batch=16,
    optimizer='AdamW',
    lr0=0.001,
    close_mosaic=15,
    name='yolov8n_mbv3_tuning_2',
    project='yolo_tuning_test'
)

"""### Konfigurasi Training Modifikasi (AdamW Tuning)

| Kategori | Parameter | Nilai | Deskripsi |
| :--- | :--- | :--- | :--- |
| **Utama** | `model` | yolov8n_mbv3.yaml | Arsitektur modifikasi MobileNetV3 |
| | `imgsz` | 800 | Resolusi input gambar (High Resolution) |
| | `epochs` | 50 | Total siklus pelatihan |
| | `batch` | 16 | Jumlah sampel per batch |
| **Optimizer** | `optimizer` | AdamW | Adaptive Moment Estimation with Weight Decay |
| | `lr0` | 0.001 | Initial Learning Rate (Lebih kecil untuk stabilitas) |
| | `momentum` | 0.937 | Beta1 untuk AdamW |
| | `weight_decay` | 0.0005 | Penalti regularisasi |
| **Loss Gain** | `box` | 7.5 | Bobot penalti Box Loss |
| | `cls` | 0.5 | Bobot penalti Classification Loss |
| | `dfl` | 1.5 | Bobot Distribution Focal Loss |
| **Augmentasi** | `mosaic` | 1.0 | Aktif (Penggabungan 4 gambar) |
| | `close_mosaic`| 15 | Mosaic dimatikan pada 15 epoch terakhir |
| | `warmup_epochs`| 3.0 | Durasi fase pemanasan awal |
| **Lainnya** | `iou` | 0.7 | NMS Threshold (Penyaringan kotak dobel) |
"""

from ultralytics import YOLO

model_eval = YOLO('/content/runs/detect/yolo_tuning_test/yolov8n_mbv3_tuning_2/weights/best.pt')

# Lakukan validasi ulang secara singkat
print("\n--- Menghitung Metrik Lengkap ---")
metrik = model_eval.val(data='/content/drive/MyDrive/RDD2022_JP_YOLO/rdd_data_jp_local.yaml')

# Panggil metrik spesifik
print(f"mAP@50    : {metrik.box.map50:.4f}")
print(f"mAP@75    : {metrik.box.map75:.4f}")
print(f"mAP@50-95 : {metrik.box.map:.4f}")

"""##**TUNING - 4**"""

from ultralytics import YOLO

model = YOLO('yolov8n_mbv3.yaml')

model.train(
    data='/content/drive/MyDrive/RDD2022_JP_YOLO/rdd_data_jp_local.yaml',
    epochs=50,
    imgsz=800,
    batch=16,
    optimizer='AdamW',
    lr0=0.001,
    box=15.0,           # Push akurasi lokasi retakan
    cls=2.0,            # Push akurasi klasifikasi tipe kerusakan
    close_mosaic=20,    # KUNCI UTAMA: 20 epoch terakhir fokus gambar bersih
    warmup_epochs=3,    # Percepat masuk ke fase belajar utama
    name='yolov8n_mbv3_tuning_3',
    project='yolo_tuning_test'
)

"""### Konfigurasi Training Modifikasi (High Gain & Early Close)

| Kategori | Parameter | Nilai | Deskripsi |
| :--- | :--- | :--- | :--- |
| **Utama** | `model` | yolov8n_mbv3.yaml | Arsitektur modifikasi MobileNetV3 |
| | `imgsz` | 800 | Resolusi tinggi untuk detail retakan |
| | `epochs` | 50 | Total siklus pelatihan |
| | `batch` | 16 | Jumlah sampel per batch |
| **Optimasi** | `optimizer` | AdamW | Optimizer adaptif (Adam with Weight Decay) |
| | `lr0` | 0.001 | Initial Learning Rate stabil |
| **Loss Gain** | `box` | 15.0 | Bobot Box Loss dinaikkan 2x lipat (Agresif) |
| | `cls` | 2.0 | Bobot Class Loss dinaikkan 4x lipat |
| | `dfl` | 1.5 | Bobot Distribution Focal Loss |
| **Augmentasi** | `mosaic` | 1.0 | Aktif di awal training |
| | `close_mosaic`| 20 | Mosaic dimatikan lebih awal (20 epoch terakhir) |
| | `warmup_epochs`| 3 | Durasi fase pemanasan awal |
| **Lainnya** | `iou` | 0.7 | NMS Threshold |
| | `nc` | 4 | Jumlah kelas kerusakan jalan utama |
"""

from ultralytics import YOLO

model_eval = YOLO('/content/runs/detect/yolo_tuning_test/yolov8n_mbv3_tuning_3/weights/best.pt')

# Lakukan validasi ulang secara singkat
print("\n--- Menghitung Metrik Lengkap ---")
metrik = model_eval.val(data='/content/drive/MyDrive/RDD2022_JP_YOLO/rdd_data_jp_local.yaml')

# Panggil metrik spesifik
print(f"mAP@50    : {metrik.box.map50:.4f}")
print(f"mAP@75    : {metrik.box.map75:.4f}")
print(f"mAP@50-95 : {metrik.box.map:.4f}")

"""##**TUNING - 5**"""

from ultralytics import YOLO

model = YOLO('yolov8n_mbv3.yaml')

model.train(
    data='/content/drive/MyDrive/RDD2022_JP_YOLO/rdd_data_jp_local.yaml',
    epochs=50,
    imgsz=800,
    batch=16,
    optimizer='AdamW',
    lr0=0.01,
    cos_lr=True,
    close_mosaic=20,
    name='yolov8n_mbv3_tuning_4',
    project='yolo_tuning_test'
    )

from ultralytics import YOLO

model_eval = YOLO('/content/runs/detect/yolo_tuning_test/yolov8n_mbv3_tuning_4/weights/best.pt')

# Lakukan validasi ulang secara singkat
print("\n--- Menghitung Metrik Lengkap ---")
metrik = model_eval.val(data='/content/drive/MyDrive/RDD2022_JP_YOLO/rdd_data_jp_local.yaml')

# Panggil metrik spesifik
print(f"mAP@50    : {metrik.box.map50:.4f}")
print(f"mAP@75    : {metrik.box.map75:.4f}")
print(f"mAP@50-95 : {metrik.box.map:.4f}")

"""##**TUNING - 6**"""

from ultralytics import YOLO

model = YOLO('yolov8n_mbv3.yaml')

model.train(
    data='/content/drive/MyDrive/RDD2022_JP_YOLO/rdd_data_jp_local.yaml',
    epochs=50,
    imgsz=800,
    batch=16,
    optimizer='SGD',
    lr0=0.01,
    freeze=10,
    name='yolov8n_mbv3_tuning_5',
    project='yolo_tuning_test'
    )

from ultralytics import YOLO

model_eval = YOLO('/content/runs/detect/yolo_tuning_test/yolov8n_mbv3_tuning_5/weights/best.pt')

# Lakukan validasi ulang secara singkat
print("\n--- Menghitung Metrik Lengkap ---")
metrik = model_eval.val(data='/content/drive/MyDrive/RDD2022_JP_YOLO/rdd_data_jp_local.yaml')

# Panggil metrik spesifik
print(f"mAP@50    : {metrik.box.map50:.4f}")
print(f"mAP@75    : {metrik.box.map75:.4f}")
print(f"mAP@50-95 : {metrik.box.map:.4f}")

"""##**NYIMPEN KE GDRIVE**"""

import shutil
import os

sumber_runs = '/content/runs'
tujuan_drive = '/content/drive/MyDrive/RDD2022_JP_YOLO/Hasil_Training_Skripsi'

if os.path.exists(sumber_runs):
    shutil.copytree(sumber_runs, tujuan_drive, dirs_exist_ok=True)
    print(f" Selesai! Folder 'runs' sudah aman di: {tujuan_drive}")
else:
    print(" Error: Folder 'runs' tidak ditemukan. Pastikan proses training sudah berjalan.")

import shutil
import os

nama_folder_training = 'yolov8n_mbv3_tuning_4'
folder_project = 'yolo_tuning_test'
# ------------------------------------------------

sumber_skenario = f'/content/runs/detect/{folder_project}/{nama_folder_training}'
tujuan_drive = f'/content/drive/MyDrive/RDD2022_JP_YOLO/Hasil_Training_Skripsi/Tuning_Manual/{nama_folder_training}'

if os.path.exists(sumber_skenario):
    os.makedirs(tujuan_drive, exist_ok=True)
    shutil.copytree(sumber_skenario, tujuan_drive, dirs_exist_ok=True)

    print(f"Backup Berhasil!")
    print(f"Folder '{nama_folder_training}' sudah aman di Drive.")
    print(f"Path: {tujuan_drive}")
else:
    print(f" Error: Folder {sumber_skenario} tidak ditemukan.")